---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk

inputs:
- name: concourse-example
outputs:
- name: artifacts
  path: concourse-example/addition/build/libs/

run:
  path: "concourse-example/gradlew"
  args: ["--build-file", "concourse-example/build.gradle", "--settings-file", "concourse-example/settings.gradle", "addition:clean", "addition:test", "addition:build"]

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false