---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk

inputs:
- name: concourse-example

run:
  path: "concourse-example/gradlew"
  args: ["--build-file", "concourse-example/build.gradle", "--settings-file", "concourse-example/settings.gradle" "addition:clean", "addition:test"]

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false