---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk

inputs:
- name: concourse-example

run:
  path: "concourse-example/gradlew"
  args: ["addition:clean", "addition:test"]

params:
  TERM: -dumb