resources:
  - name: helloworld-src-git
    type: git
    source:
      uri: https://github.com/lukemueller/concourse-example
      branch: master

jobs:
  - name: test
    plan:
      - get: helloworld-src-git
        trigger: true
      - task: test
        file: helloworld-src-git/ci/tasks/test/task.yml
  - name: deploy-dev
    serial: true
    plan:
      - get: helloworld-src-git
        trigger: true
        passed: [test]
      - task: deploy-dev
        file: helloworld-src-git/ci/tasks/deploy-dev/task.yml
