resources:
- name: concourse-example
  type: git
  source:
    uri: https://github.com/lukemueller/concourse-example.git
    branch: master

jobs:
- name: unit-addition
  plan:
  - get: concourse-example
    trigger: true
  - task: unit-addition
    file: concourse-example/ci/tasks/unit-addition.yml

- name: calculator-integration
  serial: true
  plan:
  - get: concourse-example
    passed: [unit-addition]
  - task: unit-calculator
    file: concourse-example/ci/tasks/unit-calculator.yml
