resources:
- name: concourse-example
  type: git
  source:
    uri: https://github.com/lukemueller/concourse-example.git
    branch: master

jobs:
- name: addition-unit
  plan:
  - get: concourse-example
    trigger: true
  - task: unit
    file: concourse-example/ci/tasks/unit.yml